### PR TITLE
Fix possible panic from goInfo dependency

### PR DESCRIPTION
**Pull request by alanhamlett**
https://github.com/matishsiao/goInfo/pull/15

### CODE REVIEW

**Comment by gandarez** [comment]
It's still unreviewed by the maintainer :(

**Comment by alanhamlett** [comment]
Yep, because I just sent the PR upstream a few minutes ago.

**Comment by gandarez** [comment]
> Yep, because I just sent the PR upstream a few minutes ago.

lol I didn't realize that sorry

**Review by gandarez — APPROVED** [review]
Already approving but with remarks regarding file naming in the upstream PR.

**Pull request merged**
